name: "Docker tags to a markdown bullet list"
description: "Convert the docker tags to a markdown bullet list"
author: "Jizu Sun"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "heart"
  color: "red"

# Define your inputs here.
inputs:
  docker-tags:
    description: "the string of docker images tags"
    required: true

# Define your outputs here.
outputs:
  markdown-string:
    description: "the string of a markdown bullet list "
  docker-image-name:
    description: 'the string of the docker image name, without tag'

runs:
  using: node20
  main: dist/index.js
